name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install modules
        run: npm ci
      - name: Build application
        run: npm run build
      - uses: MrMeison/yc-object-storage-action@main
        with:
          accessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bucketName: ${{ secrets.BUCKET_ID }}
          sourceDir: ./dist
          clear: true
